---
name: "hub-ci"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  hub-ci:
    uses: "orbitcluster/oc-terraform-module-eks-setup/.github/workflows/main.yml@v2.17.2"
    with:
      tfvar_file_path: "hub.tfvars"
      bucket_name: "oc-backend-hub"
      approvers: "dilipsamanta, mav-sk"
      master_s3_directory: "oc-eks-hub"
      module_ref: "v2.17.2"
    secrets: inherit
